//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineElection.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch
    {
        public System.Guid batch_ID { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
        public Nullable<System.Guid> fac_ID { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
