//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineElection.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public System.Guid Person_ID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.Guid> Degree_ID { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual user user { get; set; }
    }
}
